services:
  - type: web
    name: impact-lab
    runtime: python
    region: singapore
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn config.wsgi:application"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        value: "sqlite:///db.sqlite3"
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: EMAIL_BACKEND
        value: "django.core.mail.backends.console.EmailBackend"
