# Generated by Django 6.0.6 on 2026-06-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='이름')),
                ('email', models.EmailField(max_length=254, verbose_name='이메일')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='연락처')),
                ('consultation_type', models.CharField(choices=[('admissions', '입시 컨설팅'), ('ai_lab', 'AI Lab'), ('veritas', '논술'), ('other', '기타')], max_length=20, verbose_name='상담 유형')),
                ('grade', models.CharField(blank=True, max_length=20, verbose_name='학년')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='희망 상담 날짜')),
                ('message', models.TextField(verbose_name='문의 내용')),
                ('status', models.CharField(choices=[('received', '접수'), ('confirmed', '확인'), ('completed', '완료')], default='received', max_length=20, verbose_name='상태')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='신청일')),
            ],
            options={
                'verbose_name': '상담 신청',
                'verbose_name_plural': '상담 신청',
                'ordering': ['-created_at'],
            },
        ),
    ]
