# Generated by Django 6.0.6 on 2026-06-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('university', models.CharField(max_length=100, verbose_name='대학')),
                ('category', models.CharField(choices=[('ivy', 'IVY League'), ('top20', 'Top 20'), ('top50', 'Top 50')], max_length=10, verbose_name='카테고리')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='합격 인원')),
                ('is_featured', models.BooleanField(default=False, verbose_name='메인 노출')),
            ],
            options={
                'verbose_name': '합격 실적',
                'verbose_name_plural': '합격 실적',
                'ordering': ['-year', 'category'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='파트너명')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='로고')),
                ('url', models.URLField(blank=True, verbose_name='웹사이트')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='설명')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
            ],
            options={
                'verbose_name': '파트너',
                'verbose_name_plural': '파트너',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.CharField(blank=True, max_length=300)),
                ('announcement_active', models.BooleanField(default=False)),
                ('announcement_link', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('thread_url', models.URLField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'verbose_name': '사이트 설정',
                'verbose_name_plural': '사이트 설정',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50, verbose_name='학생 이름')),
                ('admitted_school', models.CharField(max_length=100, verbose_name='합격 학교')),
                ('content', models.TextField(verbose_name='후기 내용')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='사진')),
                ('year', models.PositiveIntegerField(verbose_name='연도')),
                ('is_featured', models.BooleanField(default=False, verbose_name='메인 노출')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='순서')),
            ],
            options={
                'verbose_name': '학생 후기',
                'verbose_name_plural': '학생 후기',
                'ordering': ['order', '-year'],
            },
        ),
    ]
